### ISSUE TITLE
Pre-configured options

### ISSUE THREAD

**Issue by Neirda24** [sensiolabs/GotenbergBundle#5]
Allow something like this in configuration:
```yaml
gotenberg:
    clients:
        some_client:
            options:
                xx: yy
```

This would greatly improve re-usability
